### PR TITLE
Copy and download

### LINKED ISSUE #1: [FEATURE] Ability to copy contents or download a file
Add options in the dropdown menu of files to copy contents or download the actual file into the system

### PR DESCRIPTION
**Pull request by vhawk19**
Resolves #1 

- I had to use [file-saver](https://www.npmjs.com/package/file-saver) as pointed out by @FlorianWoelki. I used this as it has better browser support and is relatively a lightweight library. I believe the same can be done by using the <a> tag with the download attribute natively.
- I haven't added the shortcuts yet as i wasn't sure of the key map style, do you think `Alt + s` is a good choice for download file and `Alt + a` for copy contents?

### CODE REVIEW

**Comment by haxzie** [comment]
Hey @vhawk19 :wave: Thanks for the PR :raised_hands:  I guess `Alt + S` might be used by browsers for some browser features. We can maybe use `Ctrl + Alt + S` for saving and `Ctrl + Alt + C` for copying. What do you think?

**Comment by FlorianWoelki** [comment]
Hey guys 👋
What about simply using `Cmd + S` / `Strg + S`?
I mean who really does save a webpage on their desktop :D

**Comment by haxzie** [comment]
Haha, that's true @FlorianWoelki ! We might need to override the browser defaults.

**Comment by haxzie** [comment]
@vhawk19 I'm merging this PR. Since we might have multiple editors (side by side) in the future. So having a command to download/copy the file will be confusing if there are multiple files open. Anyway, I have added the commands `/s` and `/c` to the command center to download and copy the active file :raised_hands:

**Pull request merged**
