### PR TITLE
[FEAT] Move files into directory

### PR DESCRIPTION
**Pull request by FlorianWoelki**
Hello again :) 

I've added some functionality to the feature #12 

Right now the following is working:
* Move files from directory to directory
* Move files from directory to root

### CODE REVIEW

**Comment by FlorianWoelki** [comment]
Right now, the highlighting functionality is kind of "buggy". Maybe @haxzie can take a look at it.

It is because I basically store the dragging behaviour in the data part. I think it might be better when we store the "isDragging" state in the store and then apply the classes.

**Comment by haxzie** [comment]
Thanks again @FlorianWoelki, I'll have a look at it and will update in this thread once I find a fix 🙌🏼✨

**Comment by prikeshsavla** [comment]
This works great. I just have one issue with the hightlight color. The hover option darkens the bg. You can use an accent color like blue which is more common in file explorers or a lighter grey color to match the theme. maybe add an option in the theme for this color if not already there .

**Comment by FlorianWoelki** [comment]
Agreed with @prikeshsavla 
Maybe @haxzie can add this in the refinement? :)

**Comment by FlorianWoelki** [comment]
I've fixed the flashing issue by storing a Vuex state variable and updating the value of it whenever a different dragging element was hovered.

In addition, I've added a theme `--drag-over-color` and set it to `#323543`. It is a light gray used in the official Dracula specification.

**Comment by haxzie** [comment]
Nice! The implementation looks good to me :+1: The drag over color being lighter makes it looks odd, I have played around with the colors and the `--color-secondary` actually looks okay. What do you think @FlorianWoelki ?

**Comment by FlorianWoelki** [comment]
I personally think that both colors are great options. VS-Code uses a lighter one.
In the end, you will decide ;) Maybe @prikeshsavla can state his opionion.

**Comment by haxzie** [comment]
@FlorianWoelki  Cool then :raised_hands: , I have changed the color to a lighter tone and added ability to move directories as well :+1:

**Comment by prikeshsavla** [comment]
Was out of loop for a while. I'll check it out and comment on it if I have
any suggestions.

**Pull request merged**
